import os
import json

# Define the paths
IMAGE_DIR = 'images'
CONFIG_FILE = 'config.js'

# Accepted image extensions
VALID_EXTENSIONS = ('.png', '.jpg', '.jpeg', '.gif', '.webp', '.bmp')

def generate_config():
    if not os.path.exists(IMAGE_DIR):
        print(f"Creating directory: {IMAGE_DIR}")
        os.makedirs(IMAGE_DIR)
        
    # Get all valid images in the directory
    images = []
    for filename in os.listdir(IMAGE_DIR):
        if filename.lower().endswith(VALID_EXTENSIONS):
            images.append(filename)
            
    # Sort them alphabetically (optional, but good for predictable ordering)
    images.sort()
    
    # Write to config.js
    with open(CONFIG_FILE, 'w') as f:
        f.write("// Auto-generated by update_images.py\n")
        f.write(f"window.kioskImages = {json.dumps(images, indent=4)};\n")
        
    print(f"Successfully updated {CONFIG_FILE} with {len(images)} images.")

if __name__ == '__main__':
    generate_config()
